#!/usr/bin/env bash
cd Monster
echo -e "\e[33m                                                        \e[0m"
echo -e "\e[33m         |_   _/ ___|| | | |  / \  | |/ / ____|\e[0m"
echo -e "\e[33m           | | \___ \| |_| | / _ \ | ' /|  _|\e[0m"
echo -e "\e[33m           | |  ___) |  _  |/ ___ \| . \| |___\e[0m"
echo -e "\e[33m           |_| |____/|_| |_/_/   \_\_|\_\_____|\e[0m"
while(true) do
lua start.lua 
done
